### ISSUE TITLE
ES, search page external user (Nav.)

### ISSUE THREAD

**Issue by oskarholmstrom** [C4SolutionsTDDC88/front-end#91]
Actions to implement:

- [x] A imitation of actions related to S1. Check in and check out is not possible.

See document "Description of Flow":
https://docs.google.com/document/d/1stq5FIp6CGFa_t0xk_jyqTgElS2iJpeikkPCXEDkTzc/edit#

**Comment by Flippe1** [comment]
Denna är redan implementerad via tidigare issue. Loggar man som användare in utan att vara i ett rum så kan man inte checka in eller ut material men fortfarade se och söka :)
